[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview
.Requisitos funcionales
* La aplicación permitirá la utilizacion de varios roles de usuario que podran identificarse para obtener la vista de sus mapas guardados.
* Los usuarios podran realizar acciones de "feedback" (ya sea comentar, reaccionar, asociar imagenes) a los lugares añadidos.
* Cada usuario podra crear y compartir un mapa con las ubicaciones que el escoja con otros usuarios de la aplicacion.
* La visualización de los mapas permitira el uso de filtros .

.Requisitos funcionales opcionales
* Creacion de mapas para una comunidad.
* Los usuarios podran crear rutas y obtener información de nuevos lugares que puedan aparecer.
* Creación de un "Newsfeed" para estar al dia de las ultimas actualizaciones.
* Roles distintos en el sistema.


.Requisitos no funcionales
* La aplicación guardara de manera segura los datos de los usuarios que la utilicen.
* El tiempo de respuesta debe ser relativamente razonable bajo para evitar que al usuario no tenga la sensacion de que la aplicacion esta "colgada".
* La aplicación se realizara en React usando TypeScript.


[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
Los principales atributos de calidad que queremos que tenga nuestro proyecto son los siguientes:

[options="header",cols="1,2"]
|===
|Objectivo|Detalles
| _Privacidad_ | _Guardaremos la privacidad del usuario. Lo lograremos usando SOLID, que principalmente se basa en almacenar en la base de datos información a cerca del usuario cliente quién será el que nos autorice guardar dicha información._ 
| _Rendimiento_ | _Para la creación de esta aplicación queremos garantizar la máxima rapidez que se pueda a la hora de responder a las peticiones del usuario._ 
| _Usabilidad_ | _El uso de la aplicaicón debe resultar un proceso intuitivo y sencillo para el usuario cliente._
| _Mantenibilidad_ | _Procuraremos cuidar la arquitectura de la aplicación de manera que se pueda añadir, modificar o quitar funcionalidad con el menor número posible de cambios._
| _Testeabilidad_| _Nuestra aplicaicón también podrá ser testeable, es decir, estará sometida a una serie de pruebas unitarias que realizaremos para asegurar un correcto funcionamiento del sistema, además de identificar pequeños errores y poder corregirlos en tal caso._
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Cliente_ | _Ayuntamiento de Bruselas_ | _Una aplicación en la que los ciudadanos puedan disponer de mapas personalizados sobre lugares y negocios locales de la ciudad_
| _Empresa contratada_ | _HappySw_ | _Desarrollo de un software genérico que pueda ser utilizada y desplegada en otras ciudades_
| _Equipo de desarrollo_ | _Desarrolladores de HappySw_ | _Información clara y concisa sobre los requisitos de la aplicación_
| _Usuarios_ | _Ciudadanos de Bruselas_ | _Una aplicación usable y sencilla que les permita crear mapas personalizados de los lugares que les interesen_
| _Jefe de proyecto_ | _Profesores de la asignatura_ | _Desarrollo por parte de los estudiantes de una aplicación que cumpla sus criterios_
|===
