[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----
=== Usuario crea una cuenta o se loguea.
En este caso vemos la interaccion de un usuario nuevo que va a realizar por primera vez el ingreso de sesion 
o se va autenticar en el sistema.

[plantuml,"Login",png]
----
actor Bob
database Pod as "Bob's Pod"
participant API
participant LoMap
Bob -> LoMap: llamada a login() de Bob
LoMap -> API: obtener datos de Bob
API -> Pod: accede a datos de Bob access()
Pod -> LoMap: datos de Bob
LoMap -> Pod: creacion cuenta loadData()
----

=== Acceso al mapa principal
Este caso tiene lugar una vez los usuarios estan logeados dentro de la aplicacion y se va a mostrar un panel con diversas 
opciones para que el usuario elija que mapa quiere acceder.
[plantuml,"InteractiveMap_01",png]
----
----


=== Interaccion con el mapa
Veremos el caso en el que el usuario interacciona con el mapa para añadir lugares o realizar interacciones tales
como escribir comentarios en ellos.

[plantuml,"InteractiveMap_01",png]
----
actor Bob
database MongoDB
participant API
participant LoMap
Bob -> LoMap: vision del mapa
LoMap -> API: obtener datos de click
API -> LoMap: envuelve los datos en objeto
LoMap -> Bob: accion de guardar (o editar)
Bob -> LoMap: enviar accion
LoMap -> MongoDB: almacena el lugar actualizado
----
