[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****


=== Usuario crea una cuenta o se loguea.
En este caso vemos la interaccion de un usuario nuevo que va a realizar por primera vez el ingreso de sesion 
o se va autenticar en el sistema.

[plantuml,"Login",png]
----
actor Bob
participant API
participant LoMap
database Pod as "Bob's Pod"
Bob -> LoMap: llamada a login() de Bob
LoMap -> API: obtener datos de Bob
API -> Pod: accede a datos de Bob access()
Pod --> LoMap: datos de Bob
LoMap -> Pod: creacion cuenta loadData()
----

=== Accesos de opciones
Este caso tiene lugar una vez los usuarios estan logeados dentro de la aplicacion y se va a mostrar un panel con diversas 
opciones para que el usuario elija entre todas ellas, como por ejemplo compartir con otros usuarios.
[plantuml,"InteractiveMap_00",png]
----
actor Bob
actor Alice
participant LoMap
participant Pod
database MongoDB
Bob -> LoMap: compartirCon
LoMap -> MongoDB: extraePersonas
MongoDB -> MongoDB: guarda lugar en los usuarios
MongoDB --> Pod: actualiza pods de usuarios
MongoDB --> LoMap: confirmacion
LoMap --> Bob: success
LoMap -> Alice: notificacion
----

=== Interaccion con el mapa
Veremos el caso en el que el usuario interacciona con el mapa para añadir lugares o realizar interacciones tales
como escribir comentarios en ellos.

[plantuml,"InteractiveMap_01",png]
----
actor Bob
participant API
participant LoMap
database MongoDB
Bob -> LoMap: vision del mapa
LoMap -> Bob: vista
Bob -> LoMap: actionClick()
LoMap -> API: obtener datos de click
API --> LoMap: envuelve los datos en objeto
LoMap -> Bob: accion de guardar (o editar)
Bob -> LoMap: enviar accion
LoMap -> MongoDB: almacena el lugar actualizado
----